apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: message
      description: The message to print
      default: hello
    - name: repository
      description: The git repo
      default: "https://github.com/skaegi/hello-containers"
    - name: apikey
      description: the ibmcloud api key 
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: pipeline-pvc
          value: pipelinerun-$(uid)-pvc
        - name: message
          value: $(params.message)
        - name: repository
          value: $(params.repository)
        - name: apikey
          value: $(params.apikey)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: message
      value: binding message
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
      params:
        - name: message-l
          value: Hello from the Manual Triggers EventListener!